version: '3'

networks:
  net:
    driver: bridge

services:
  app:
    build: .
    ports:
      - 3000:3000
    container_name: app
    restart: always
    environment:
      PORT: 3000
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_DB: node
    depends_on:
      - db
    networks:
      - net
    
  db:
    platform: linux/amd64 # for mac
    image: mysql:5.7
    restart: always
    tty: true
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node
    networks:
      - net
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:stable
    restart: always
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - net
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf